"""fix relationship between company and users tables

Revision ID: 0e57a842dcaf
Revises: 36efbca34d3a
Create Date: 2024-11-05 11:04:50.240670

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e57a842dcaf"
down_revision: Union[str, None] = "36efbca34d3a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
