"""change company admin relationship from one to many to one to one

Revision ID: 1f12dc4da0d0
Revises: 2c7a0b2ea39b
Create Date: 2024-11-06 19:41:17.640574

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f12dc4da0d0"
down_revision: Union[str, None] = "2c7a0b2ea39b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
