"""fix company and users relationship

Revision ID: 2c7a0b2ea39b
Revises: 0e57a842dcaf
Create Date: 2024-11-06 18:29:21.956617

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c7a0b2ea39b"
down_revision: Union[str, None] = "0e57a842dcaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
