"""update relationship between company and user for the admin case

Revision ID: 36efbca34d3a
Revises: c3f807065391
Create Date: 2024-11-04 23:30:38.934251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36efbca34d3a'
down_revision: Union[str, None] = 'c3f807065391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('admin_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'companies', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'admin_id')
    # ### end Alembic commands ###
