"""update comapnies table add columns

Revision ID: c3f807065391
Revises: 4ef994289866
Create Date: 2024-11-04 23:15:28.251969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3f807065391'
down_revision: Union[str, None] = '4ef994289866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('description', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('website', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('contact_email', sa.String(), nullable=False))
    op.add_column('companies', sa.Column('contact_phone', sa.String(), nullable=False))
    op.add_column('companies', sa.Column('street', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('city', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('state', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('postal_code', sa.String(), nullable=False))
    op.add_column('companies', sa.Column('country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'country')
    op.drop_column('companies', 'postal_code')
    op.drop_column('companies', 'state')
    op.drop_column('companies', 'city')
    op.drop_column('companies', 'street')
    op.drop_column('companies', 'contact_phone')
    op.drop_column('companies', 'contact_email')
    op.drop_column('companies', 'website')
    op.drop_column('companies', 'description')
    # ### end Alembic commands ###
